### ISSUE TITLE
Can't open in 4.21

### ISSUE THREAD

**Issue by flops0801** [Deams51/CoverGenerator-UE4#12]
Hi,
I can see and activate this plugin in the project but if I restart, the engine can't open the project, because it says, that the plugin was made with a different version of Unreal Engine. 

Is there anything I have to mind by adding it into plugin folder?

**Comment by Cytokinetik** [comment]
Create a new, blank, 4.21 C++ project. Make a plugins folder in the normal location, and copy the plugin folder into there. Delete the binaries and intermediate folders in the plugin directory, then right click the .uplugin file and edit with notepad. Change the version to 4.21 in the file, save, then open the C++ project and let the plugin rebuild and everything should work fine.

**Comment by flops0801** [comment]
Thank you verry much, I have seen this late. Does it also works with BP projects?

**Comment by Deams51** [comment]
It doesn't come with binaries, so you will have to build it yourself in a code project. But then you should be able to use it in a BP only project if you copy/paste the binaries.
