### ISSUE TITLE
Update to 4.16.1

### ISSUE THREAD

**Issue by HeadClot** [Deams51/CoverGenerator-UE4#2]
Hey would it be possible to update this plugin to 4.16.1?

**Comment by mhoangvslev** [comment]
@HeadClot @Deams51  I managed to make it compatible to 4.17 (thus 4.16.x) and ask the author for merge

**Comment by Azaratur** [comment]
@mhoangvslev  i try your version but did not work on 4.16.3 do you have any idea?

**Comment by mhoangvslev** [comment]
@Azaratur Make sure you rebuild the solution instead. Otherwise, I might need a screenshot or little bit more info in order to help xD

**Comment by Deams51** [comment]
Merged the PR from @mhoangvslev 
If you still have any issues @HeadClot and @Azaratur please post more information :)

**Comment by Azaratur** [comment]
Thanks Deams51!
