### ISSUE TITLE
Failed to load on 4.17.1

### ISSUE THREAD

**Issue by fab5741** [Deams51/CoverGenerator-UE4#5]
![image](https://user-images.githubusercontent.com/7713254/31487237-52725c84-af3a-11e7-851c-20422816f77a.png)

Is that because of my version ?

**Comment by Deams51** [comment]
Have you tried recompiling the plugin? 
I ran tests on 4.17 and didn't get any issues.

**Comment by Deams51** [comment]
Haven't heard back from you, so closing the issue for now.
