### ISSUE TITLE
Missing Binaries

### ISSUE THREAD

**Issue by KrisManning1** [Deams51/CoverGenerator-UE4#8]
Everytime I load up my project using this plugin I get an error stating the Binaries are either missing or imcompatible with the version of the engine. 

Can I ask what version of UE4 this was made with and can it work with 4.18?
![coverpluginissue](https://user-images.githubusercontent.com/41302218/42772525-a1b1f274-8922-11e8-9748-71070b3e99d6.PNG)

**Comment by Deams51** [comment]
A bit late, but it's possible that you did not recompile the binaries after adding the plugin to the project.
