### ISSUE TITLE
Converting it on 4.20.3

### ISSUE THREAD

**Issue by Azaratur** [Deams51/CoverGenerator-UE4#9]
I am tring to convert it to 4.20.3, unfortunately after fixing some issue i got some linker error.
Did somebody convert it at once?

**Comment by Azaratur** [comment]
Ok i did recompile it. Now i will check if it's working.
Many files was moved on ue 4.20.3 and i had to change many path.

**Comment by Deams51** [comment]
Pushed an update for 4.21 so closing this issue. :)

**Comment by ANTEVETY** [comment]
@Deams51 Very useful plugin! Thank you for not refusing to update.
